/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package assets.waves
{
	import flash.utils.ByteArray;
	
	[Embed(source="testLevel.txt",mimeType="application/octet-stream")]
	
	public class AssetTestLevel extends ByteArray
	{
	
	}
}