/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package assets.creeps.ranged
{
	import flash.display.Bitmap;
	
	[Embed(source="normal.png")]
	
	public class AssetNormal extends Bitmap
	{
	
	}
}