/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package assets.heroes
{
	import flash.display.Bitmap;
	
	[Embed(source="odin.png")]
	
	public class AssetOdin extends Bitmap
	{
	
	}
}