/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package assets.creeps
{
	import flash.display.Bitmap;
	
	[Embed(source="fire.png")]
	
	public class AssetFire extends Bitmap
	{
	
	}
}