/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package assets.states
{
	import flash.display.Bitmap;
	
	[Embed(source="endGameDefeat.png")]
	
	public class AssetEndGameDefeat extends Bitmap
	{
	
	}
}