/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package assets.creeps.melee
{
	import flash.display.Bitmap;
	
	[Embed(source="normal2.png")]
	
	public class AssetNormal2 extends Bitmap
	{
	
	}
}