/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package assets.heroSelect
{
	import flash.display.Bitmap;
	
	[Embed(source="SelectHero.png")]
	
	public class AssetSelectHero extends Bitmap
	{
	
	}
}