/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package assets.skills
{
	import flash.display.Bitmap;
	
	[Embed(source="backgroundBlue.png")]
	
	public class AssetBackgroundBlue extends Bitmap
	{
	
	}
}