/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package assets.themes
{
	import flash.media.Sound;
	
	[Embed(source="intro.mp3")]
	
	public class AssetIntro extends Sound
	{
	
	}
}